repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: custom-pre-commit
        name: Golang pre-commit script
        entry: sh
        language: system
        args: [ "pre-commit.sh" ]
        require_serial: true
