version: '3.9'

services:
  daps-backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: ["air", "migrate", "&&", "air", "serve"]
    env_file:
      - backend/.env
    ports:
      - "11001:11001"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend:/daps/backend

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dapsname
      - MYSQL_USER=dapsuser
      - MYSQL_PASSWORD=dapspw
      - MYSQL_TCP_PORT=11306
    ports:
      - "11306:11306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "db", "-u$$MYSQL_USER", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 10
#    volumes:
#      - my-datavolume:/var/lib/mysql

  redis:
    image: redis:alpine
    command: [ redis-server, --port, "10379" ]

#volumes:
#  my-datavolume: