-- +goose Up
DROP TABLE IF EXISTS daps_todos;
DROP TABLE IF EXISTS daps_categories;
DROP TABLE IF EXISTS deselflopment_users;
DROP TABLE IF EXISTS daps_category_users;
DROP TABLE IF EXISTS deselflopment_emails;

CREATE TABLE deselflopment_users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    name VARCHAR(128) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    admin TINYINT NOT NULL DEFAULT 0,
    active TINYINT NOT NULL DEFAULT 0,
    activation_code VARCHAR(50) UNIQUE,
    reset_password_code VARCHAR(50) UNIQUE,
    language VARCHAR(50) NOT NULL DEFAULT 'es',
    auto_suggest TINYINT NOT NULL DEFAULT 0
);


CREATE TABLE daps_categories (
     id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
     deleted_at TIMESTAMP NULL DEFAULT NULL,
     name VARCHAR(128) NOT NULL,
     description TEXT NULL DEFAULT NULL,
     shared TINYINT NOT NULL DEFAULT 0,
     notifiable TINYINT NOT NULL DEFAULT 0,
     custom TINYINT NOT NULL DEFAULT 0,
     owner_id INT UNSIGNED NULL DEFAULT NULL,
     FOREIGN KEY(owner_id) REFERENCES deselflopment_users(id) ON DELETE CASCADE,
     UNIQUE KEY (name, owner_id)
);

CREATE TABLE daps_category_users (
     id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     category_id INT UNSIGNED NOT NULL REFERENCES daps_categories(id) ON DELETE CASCADE,
     user_id INT UNSIGNED NOT NULL REFERENCES deselflopment_users(id) ON DELETE CASCADE
);

CREATE TABLE daps_todos (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    name VARCHAR(128) NOT NULL,
    description TEXT NULL DEFAULT NULL,
    completed TINYINT NOT NULL DEFAULT 0,
    completed_at TIMESTAMP NULL DEFAULT NULL,
    active TINYINT NOT NULL DEFAULT 1,
    priority INT UNSIGNED NOT NULL DEFAULT 1,
    category_id INT UNSIGNED NOT NULL,
    link TEXT NULL DEFAULT NULL,
    recurring TINYINT NOT NULL DEFAULT 0,
    recurrency VARCHAR(50) NULL DEFAULT NULL,
    started_at TIMESTAMP NULL DEFAULT NULL,
    suggestable TINYINT NOT NULL DEFAULT 1,
    suggested TINYINT NOT NULL DEFAULT 0,
    suggested_at TIMESTAMP NULL DEFAULT NULL,
    owner_id INT UNSIGNED NOT NULL,
    FOREIGN KEY(category_id) REFERENCES daps_categories(id) ON DELETE CASCADE,
    FOREIGN KEY(owner_id) REFERENCES deselflopment_users(id) ON DELETE CASCADE,
    UNIQUE KEY (name, category_id, owner_id)
);

CREATE TABLE deselflopment_emails (
    id int UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    from_email VARCHAR(255) NOT NULL,
    source VARCHAR(50) NULL DEFAULT NULL,
    to_email VARCHAR(255) NOT NULL,
    recipient VARCHAR(128) NOT NULL,
    sent TINYINT NOT NULL DEFAULT 0,
    error_message TEXT NULL DEFAULT NULL,
    user_id INT UNSIGNED NULL REFERENCES deselflopment_users(id) ON DELETE CASCADE
);

-- +goose Down