-- +goose Up
CREATE TABLE daps_topics (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    name VARCHAR(128) NOT NULL,
    owner_id INT UNSIGNED NULL DEFAULT NULL,
    FOREIGN KEY(owner_id) REFERENCES deselflopment_users(id) ON DELETE CASCADE,
    UNIQUE KEY (name, owner_id)
);


CREATE TABLE daps_notes (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    content TEXT NOT NULL,
    shared TINYINT NOT NULL DEFAULT 0,
    subtopic_id INT UNSIGNED NULL DEFAULT NULL,
    FOREIGN KEY(subtopic_id) REFERENCES daps_topics(id) ON DELETE CASCADE,
    owner_id INT UNSIGNED NULL DEFAULT NULL,
    FOREIGN KEY(owner_id) REFERENCES deselflopment_users(id) ON DELETE CASCADE
);

CREATE TABLE daps_note_users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    note_id INT UNSIGNED NOT NULL REFERENCES daps_notes(id) ON DELETE CASCADE,
    user_id INT UNSIGNED NOT NULL REFERENCES deselflopment_users(id) ON DELETE CASCADE
);

CREATE TABLE daps_note_topics (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    note_id INT UNSIGNED NOT NULL REFERENCES daps_notes(id) ON DELETE CASCADE,
    topic_id INT UNSIGNED NOT NULL REFERENCES daps_topics(id) ON DELETE CASCADE
);
-- +goose Down